// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/google/uuid"
)

type Cluster struct {
	Uuid     uuid.UUID
	Name     string
	Endpoint string
}

type ClusterConfig struct {
	ID          int64
	ClusterUuid uuid.UUID
	ConfigType  int64
	Config      string
}

type Host struct {
	Uuid     uuid.UUID
	Fqdn     string
	NodeType int64
}

type HostCluster struct {
	HostUuid    []byte
	ClusterUuid uuid.UUID
}

type HostProfile struct {
	HostUuid  []byte
	ProfileID int64
}

type Patch struct {
	ID           int64
	ProfileID    int64
	Controlplane int64
	Worker       int64
	Host         []byte
	Patch        string
}

type Profile struct {
	ID   int64
	Name string
}
