// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/google/uuid"
)

type Host struct {
	Uuid     uuid.UUID
	Fqdn     string
	NodeType string
}

type HostCluster struct {
	HostUuid    []byte
	ClusterUuid uuid.UUID
}

type HostProfile struct {
	HostUuid  []byte
	ProfileID int64
}

type Patch struct {
	ID        int64
	ProfileID int64
	NodeType  string
	Fqdn      string
	Patch     string
}

type Profile struct {
	ID   int64
	Name string
}
