// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/google/uuid"
)

type Cluster struct {
	Uuid     uuid.UUID
	Name     string
	Endpoint string
}

type ClusterConfig struct {
	ID          int64
	ClusterUuid uuid.UUID
	ConfigType  string
	Config      string
}

type Host struct {
	Uuid     uuid.UUID
	Fqdn     string
	NodeType string
}

type HostCluster struct {
	HostUuid    uuid.UUID
	ClusterUuid uuid.UUID
}

type HostProfile struct {
	HostUuid  uuid.UUID
	ProfileID int64
}

type Patch struct {
	ID        int64
	ProfileID int64
	NodeType  string
	Fqdn      string
	Patch     string
}

type Profile struct {
	ID   int64
	Name string
}
