// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Cluster struct {
	ID       int64
	Name     string
	Endpoint string
}

type ClusterConfig struct {
	ID       int64
	ClusID   int64
	NodeType int64
	Config   string
}

type Host struct {
	ID       int64
	Fqdn     string
	NodeType int64
	Network  string
}

type HostCluster struct {
	HostID int64
	ClusID int64
}

type HostProfile struct {
	HostID    int64
	ProfileID int64
}

type NodeType struct {
	ID   int64
	Name string
}

type Patch struct {
	ID        int64
	ProfileID sql.NullInt64
	Patch     string
}

type Profile struct {
	ID   int64
	Name string
}
