// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Base struct {
	ID     int64
	Name   string
	Config string
}

type Host struct {
	ID       int64
	Fqdn     string
	BaseType int64
	Network  string
}

type HostProfile struct {
	HostID    int64
	ProfileID int64
}

type Patch struct {
	ID        int64
	ProfileID sql.NullInt64
	Patch     string
}

type Profile struct {
	ID   int64
	Name string
}
